sudo: 'false'
dist: trusty
language: node_js
node_js: '9'
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
    - node_modules
env:
  global:
    - secure: >-
        eWD6BSj0vroZbR8I2v5vQuer6R2grmVjJ6pTe6INyfOFFt2xIh3WcXi/afmAjWlgMZ/yAx7YfgmwI8qpN8ZYDsDvB1MHitl1N5MhaGGwBxd2Vpp1WJn8SRrplsnHrOZtwPqpVuAu4bsa8/GxNwnP2qJHmYsPhFd3dMcguViIgo8=
    - secure: >-
        CgrPN2wzwicrDc2SnJ8ygjpk0T3o6oDPT/5iXorirqaCFwNA+9O+1PQmjWYL3VCUVkHmm2QdOq78zIsWY3MRGaLKV0hMs5rRxRQPfVSC7AB+PQvHIHxj6Ay6tR3/jnHgd0UQlF6aGhS2hKkgWNtWdtlMMyVjPp+aVTSJGIK4kZE=
install: ./travis_scripts/install.sh
before_script: ./travis_scripts/before_script.sh
script: ./travis_scripts/script.sh
